### ISSUE TITLE
Run profile.sh failed

### ISSUE THREAD

**Issue by QuantumLiu** [Thmen/EGVSR#11]
```
bash profile.sh BI TecoGAN 3x540x960
Traceback (most recent call last):
  File "./codes/main.py", line 13, in <module>
    from metrics.metric_calculator import MetricCalculator
  File "/home/tianqing/pyprojects/EGVSR/codes/metrics/metric_calculator.py", line 11, in <module>
    from .LPIPS.models.dist_model import DistModel
  File "/home/tianqing/pyprojects/EGVSR/codes/metrics/LPIPS/models/__init__.py", line 11, in <module>
    from metrics.LPIPS.models import dist_model
  File "/home/tianqing/pyprojects/EGVSR/codes/metrics/LPIPS/models/dist_model.py", line 21, in <module>
    from . import networks_basic as networks
  File "/home/tianqing/pyprojects/EGVSR/codes/metrics/LPIPS/models/networks_basic.py", line 15, in <module>
    import metrics.LPIPS.models as util
AttributeError: module 'metrics.LPIPS' has no attribute 'models'
```

**Comment by Thmen** [comment]
fixed in #28
